version: "3.8"

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: ./server
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - secretKey=ShivkantChauhan_secretKey
    depends_on:
      - db
    command: node server.js
  